GET http://localhost:3500/student/allStudents

###
POST http://localhost:3500/student/signup
Content-Type: application/json

{
    "roll":"21071a3262",
    "name":"Shreya",
    "mail":"shreya@gmail.com",
    "batch":"VNR_2026_B1",
    "section":"CSBS",
    "password":"shreya",
    "position" :"student"
}

###
POST http://localhost:3500/student/login
Content-Type:  application/json

{
    "roll":"21071A05T2",
    "password":"nithish"
}

### Mentor

GET http://localhost:3500/mentor/allMentors

###
POST http://localhost:3500/mentor/signup
Content-Type: application/json

{
    "roll": "21071a05e5",
    "name": "G. Pallavi Reddy",
    "mail": "shreyakondurukvs@gmial.com",
    "batch": "2022_B1",
    "section": "CSBS",
    "password":"vnrvjiet",
    "position" :"mentor"
}

###
POST http://localhost:3500/mentor/login
Content-Type:  application/json

{
    "roll":"21071A3262",
    "password":"vnrvjiet"
}

### Admin

GET http://localhost:3500/admin/allAdmins

###
POST http://localhost:3500/admin/signup
Content-Type: application/json

{
    "roll":"21071a0565",
    "name":"V.Manasa",
    "mail":"manasavirivinti@gmail.com",
    "batch":"2022_B1",
    "section":"CSE-C",
    "password":"srujana",
    "position" :"admin"
}

###
POST http://localhost:3500/admin/login
Content-Type:  application/json

{
    "roll":"21071A05E5",
    "password":"pallavi"
}